# Generated by Django 5.0.4 on 2024-05-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
