# Generated by Django 5.0.4 on 2024-05-10 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='cover_image',
            field=models.ImageField(default='cover.jpg', upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
