# Generated by Django 5.0.4 on 2024-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profilemodel_id_profilemodel_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
